modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"
issueTrackerURL="https://github.com/EwyBoy/Developers-Toolkit"

[[mods]]
modId="devkit"
version="${file.jarVersion}"
displayName="Developer's Toolkit"
displayURL="https://www.curseforge.com/minecraft/mc-mods/Developers-Toolkit"
credits=""
authors="Ewy"
description=""

[[dependencies.devkit]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.devkit]]
modId="minecraft"
mandatory=true
versionRange="[1.16.3, 1.17)"
ordering="NONE"
side="BOTH"